FROM redocly/redoc

ENV SPEC_URL=swagger.yaml

COPY openapi-schema.yaml /usr/share/nginx/html/swagger.yaml

# HTTP static content is exposed on port 80
# Example of usage:
#
# docker run -p 9000:80 papermerge/redoc:0.1.0
