name: Build

on:
  workflow_dispatch:
    inputs:
      VERSION:
        required: true
        type: string
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
    inputs:
      VERSION:
        required: true
        type: string

jobs:
  dockerhub:
    name: Publish to dockerhub
    uses: ./.github/workflows/dockerhub.yml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      VERSION: ${{ inputs.VERSION }}
  ghcr:
    name: Publish to ghcr
    uses: ./.github/workflows/ghcr.yml
    secrets:
      MY_GH_TOKEN: ${{ secrets.MY_GH_TOKEN }}
    with:
      VERSION: ${{ inputs.VERSION }}
