name: Publish to Dockerhub

on:
  workflow_dispatch:
    inputs:
      VERSION:
        required: true
        type: string
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
    inputs:
      VERSION:
        required: true
        type: string

jobs:
  build-redoc:
    name: Redoc/Build and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: papermerge/redoc:latest,papermerge/redoc:${{ inputs.VERSION }}
          file: docker/Dockerfile.redoc
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: papermerge/redoc
          readme-filepath: ./docker/README.redoc.md
          short-description: >
            Redoc based geneatred REST API reference for Papermerge

  build-swagger:
    name: Swagger/Build and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: papermerge/swagger-ui:latest,papermerge/swagger-ui:${{ inputs.VERSION }}
          file: docker/prod/Dockerfile
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: papermerge/swagger-ui
          readme-filepath: ./docker/README.swagger.md
          short-description: >
            Swagger based geneatred REST API reference for Papermerge
